/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apscalculator;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author admin
 */
public class CalculateAPSPageUCT extends javax.swing.JFrame {

    /**
     * Creates new form CalculateAPSPage
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        cmbFaculty = new javax.swing.JComboBox<>();
        lblS1 = new javax.swing.JLabel();
        lblS2 = new javax.swing.JLabel();
        lblS3 = new javax.swing.JLabel();
        lblS4 = new javax.swing.JLabel();
        lblS5 = new javax.swing.JLabel();
        lblS6 = new javax.swing.JLabel();
        txfS1 = new javax.swing.JTextField();
        txfS2 = new javax.swing.JTextField();
        txfS3 = new javax.swing.JTextField();
        txfS4 = new javax.swing.JTextField();
        txfS5 = new javax.swing.JTextField();
        txfS6 = new javax.swing.JTextField();
        btnConfirmFaculty = new javax.swing.JButton();
        btnCalculate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaInstructions = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();
        lblScore = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Calculate your APS UCT");
        jLabel1.setMaximumSize(new java.awt.Dimension(298, 48));
        jLabel1.setMinimumSize(new java.awt.Dimension(298, 48));
        jLabel1.setPreferredSize(new java.awt.Dimension(298, 48));

        cmbFaculty.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cmbFaculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Commerce", "Engineering", "Health Sciences", "Humanities", "Law", "Science" }));

        lblS1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblS1.setText("Subject 1:");

        lblS2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblS2.setText("Subject 2:");

        lblS3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblS3.setText("Subject 3:");

        lblS4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblS4.setText("Subject 4:");

        lblS5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblS5.setText("Subject 5:");

        lblS6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblS6.setText("Subject 6:");

        txfS1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txfS2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txfS3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txfS4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txfS5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txfS6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        btnConfirmFaculty.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnConfirmFaculty.setText("Confirm Faculty");
        btnConfirmFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmFacultyActionPerformed(evt);
            }
        });

        btnCalculate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        txaInstructions.setEditable(false);
        txaInstructions.setColumns(20);
        txaInstructions.setRows(5);
        txaInstructions.setText("Instructions:\nSelect the major you want to calculate \nyour APS for and press confirm Major.\n\nThen enter your 3 best elective marks(%), and if \nyou do physical science (PS) and want it counted\nenter it in subject 1 and check the box.\n\nIf you don't do an advanced program leave \nthat area blank.\n\nNow press calculate");
        txaInstructions.setMaximumSize(new java.awt.Dimension(180, 84));
        txaInstructions.setMinimumSize(new java.awt.Dimension(180, 84));
        txaInstructions.setPreferredSize(new java.awt.Dimension(180, 84));
        jScrollPane2.setViewportView(txaInstructions);

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblScore.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblScore.setText("Your score: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblS2)
                            .addComponent(lblS3)
                            .addComponent(lblS4)
                            .addComponent(lblS5)
                            .addComponent(lblS6)
                            .addComponent(lblS1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfS1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txfS2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txfS3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txfS4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txfS5, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txfS6, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCalculate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConfirmFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblScore, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(81, 81, 81))
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConfirmFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblS1)
                            .addComponent(txfS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblS2)
                            .addComponent(txfS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblS3)
                            .addComponent(txfS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblS4)
                            .addComponent(txfS4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblS5)
                            .addComponent(txfS5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblS6)
                            .addComponent(txfS6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(lblScore))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private String faculty;
    private boolean facScience;
    
    public CalculateAPSPageUCT() {
        initComponents();
        txfS5.setVisible(false);
        txfS6.setVisible(false);
        txfS4.setVisible(false);
        txfS1.setVisible(false);
        txfS2.setVisible(false);
        txfS3.setVisible(false);
        lblS3.setVisible(false);
        lblS2.setVisible(false);
        lblS1.setVisible(false);
        lblS4.setVisible(false);
        lblS6.setVisible(false);
        lblS5.setVisible(false);
        btnCalculate.setVisible(false);
        lblScore.setVisible(false);
        cmbFaculty.setEnabled(true);
        txaInstructions.setText("Instructions:\n" +
"Select the major you want to calculate \n" +
"your APS for and press confirm major.");
        
    }
    
    private void DisplaySubjects(){
        txfS5.setVisible(true);
        txfS6.setVisible(true);
        txfS4.setVisible(true);
        txfS1.setVisible(true);
        txfS2.setVisible(true);
        txfS3.setVisible(true);
        lblS3.setVisible(true);
        lblS2.setVisible(true);
        lblS1.setVisible(true);
        lblS4.setVisible(true);
        lblS5.setVisible(true);
        lblS6.setVisible(true);
        btnCalculate.setVisible(true);
        lblScore.setVisible(true);
    }/*displays fields for student
    to enter their marks once faculty has been confirmed to reduce confusion*/
    
    private void commerceSelected(){
        lblS1.setText("Maths:");
        lblS2.setText("English:");
    }/*displays what subjects are 
    required based on the faculty*/
    
    private void engineeringSelected(){
        lblS1.setText("Maths:");
        lblS2.setText("Physical Science:");
        lblS3.setText("English:");
    }
    
    private void humanitiesSelected(){
        lblS1.setText("English:");
    }
    
    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        Calculate cal = new Calculate();
        DB database = new DB();
        
        cal.setFacScience(facScience);
        cal.setIsUct(true);
        String[] textFields = {txfS1.getText(), txfS2.getText(), txfS3.getText(),
            txfS4.getText(), txfS5.getText(), txfS6.getText()};//declares and assigns value to the textfield array to be used in the calculate class
        String[] labels = {lblS1.getText(), lblS2.getText(), lblS3.getText(), 
            lblS4.getText(), lblS5.getText(), lblS6.getText()};//declares and assigns value to the label array to be used in the calculate class
        int score = cal.calculateAPS(textFields, labels);
        
        if (!cal.hasErrors()) {//if there are no errors in the data entered then user is asked if they want to save their score
            lblScore.setText("Your score: " + score);
            int input = JOptionPane.showConfirmDialog(null, 
          "Do you want to save this score to your user profile?", 
          "Confirm score save", JOptionPane.YES_NO_OPTION, 
          JOptionPane.QUESTION_MESSAGE);
            if (input == 0) {
                try {//saves users score to database
                    database.updateTbl("UPDATE UserResults SET APSuct = " + score + 
                            ", UctFaculty = '" + faculty + "' WHERE Username = '" 
                            + LoginPage.getUserLoggedIn() + "'");//stores user score in access database
                } catch (SQLException ex) {
                    System.out.println(ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, cal.getError());//shows error message
        }
    }//GEN-LAST:event_btnCalculateActionPerformed
    /*Runs processes to calculate and store the users APS*/
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        Home h = new Home();
        h.setVisible(true);
        h.setSize(800,550);
        h.setResizable(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnConfirmFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmFacultyActionPerformed
        //below is code that customizes the screen based on what faculty is selected
        faculty = cmbFaculty.getSelectedItem()+ "";
        
        txaInstructions.setText("Instructions:\n" +
        "Select the major you want to calculate \n" +
        "your APS for and press confirm Major.\n" + "\n" +
        "Then enter your mark for the required subjects\n" +
        "then your next highest marks for any subject\n"
        + "excluding LO and Further study programs.\n" + "\n" +
        "Now press calculate");
            
        DisplaySubjects();
        btnConfirmFaculty.setVisible(false);
        cmbFaculty.setEnabled(false);
        
        if (faculty.equals("Commerce")) {
            commerceSelected();
        } else if (faculty.equals("Engineering")) {
            engineeringSelected();
        } else if (faculty.equals("Health Sciences")) {
            engineeringSelected();
        } else if (faculty.equals("Humanities")) {
            humanitiesSelected();
        } else if (faculty.equals("Law")) {
            humanitiesSelected();
        } else if (faculty.equals("Science")) {
            engineeringSelected();
            facScience = true;
        }
    }//GEN-LAST:event_btnConfirmFacultyActionPerformed
    /*alters gui based on what faculty usr selects*/
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculateAPSPageUCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculateAPSPageUCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculateAPSPageUCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculateAPSPageUCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculateAPSPageUCT().setVisible(true);
                
            }
        });
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnConfirmFaculty;
    private javax.swing.JComboBox<String> cmbFaculty;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblS1;
    private javax.swing.JLabel lblS2;
    private javax.swing.JLabel lblS3;
    private javax.swing.JLabel lblS4;
    private javax.swing.JLabel lblS5;
    private javax.swing.JLabel lblS6;
    private javax.swing.JLabel lblScore;
    private javax.swing.JTextArea txaInstructions;
    private javax.swing.JTextField txfS1;
    private javax.swing.JTextField txfS2;
    private javax.swing.JTextField txfS3;
    private javax.swing.JTextField txfS4;
    private javax.swing.JTextField txfS5;
    private javax.swing.JTextField txfS6;
    // End of variables declaration//GEN-END:variables
}

