/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apscalculator;

import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.sql.SQLException;

/**
 *
 * @author admin
 */
public class CalculateAPSPageUP extends javax.swing.JFrame {

    /**
     * Creates new form CalculateAPSPage
     */
    public CalculateAPSPageUP() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblS1 = new javax.swing.JLabel();
        lblS2 = new javax.swing.JLabel();
        lblS3 = new javax.swing.JLabel();
        lblMaths = new javax.swing.JLabel();
        lblEnglish = new javax.swing.JLabel();
        lblFal = new javax.swing.JLabel();
        txfS1 = new javax.swing.JTextField();
        txfS2 = new javax.swing.JTextField();
        txfS3 = new javax.swing.JTextField();
        txfMaths = new javax.swing.JTextField();
        txfEnglish = new javax.swing.JTextField();
        txfFal = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaInstructions = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();
        lblScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Calculate your APS UP");
        jLabel1.setMaximumSize(new java.awt.Dimension(298, 48));
        jLabel1.setMinimumSize(new java.awt.Dimension(298, 48));
        jLabel1.setPreferredSize(new java.awt.Dimension(298, 48));

        lblS1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblS1.setText("Subject 1:");

        lblS2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblS2.setText("Subject 2:");

        lblS3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblS3.setText("Subject 3:");

        lblMaths.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMaths.setText("Maths:");

        lblEnglish.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblEnglish.setText("English:");

        lblFal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFal.setText("FAL:");

        txfS1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txfS2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txfS3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txfMaths.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txfEnglish.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txfFal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        btnCalculate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        txaInstructions.setEditable(false);
        txaInstructions.setColumns(20);
        txaInstructions.setRows(5);
        txaInstructions.setText("Instructions:\nEnter your marks for your best three elective \nsubjects, not including LO, and then your marks for \nmaths, english and your FAL (Afrikaans, isiZulu, etc.)\n\nNow press calculate\n\nYour score will be displayed in the bottom right ");
        txaInstructions.setMaximumSize(new java.awt.Dimension(180, 84));
        txaInstructions.setMinimumSize(new java.awt.Dimension(180, 84));
        txaInstructions.setPreferredSize(new java.awt.Dimension(180, 84));
        jScrollPane2.setViewportView(txaInstructions);

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblScore.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblScore.setText("Your score: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblS2)
                    .addComponent(lblS3)
                    .addComponent(lblMaths)
                    .addComponent(lblEnglish)
                    .addComponent(lblFal)
                    .addComponent(lblS1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfS1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txfS2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txfS3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txfMaths, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txfEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txfFal, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblScore, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblS1)
                            .addComponent(txfS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblS2)
                            .addComponent(txfS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblS3)
                            .addComponent(txfS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaths)
                            .addComponent(txfMaths, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEnglish)
                            .addComponent(txfEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfFal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFal))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBack)
                            .addComponent(lblScore))))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        Calculate cal = new Calculate();
        DB database = new DB();
        
        cal.setIsUp(true);
        String[] textFields = {txfS1.getText(), txfS2.getText(), txfS3.getText(), 
            txfMaths.getText(), txfEnglish.getText(), txfFal.getText()};//declares and assigns value to the textfield array to be used in the calculate class
        String[] labels = {lblS1.getText(), lblS2.getText(), lblS3.getText(), 
            lblMaths.getText(), lblEnglish.getText(), lblFal.getText()};//declares and assigns value to the label array to be used in the calculate class
        int score = cal.calculateAPS(textFields, labels);
        
        if (!cal.hasErrors()) {//if there are no errors in the data entered then user is asked if they want to save their score
            lblScore.setText("Your score: " + score);
            int input = JOptionPane.showConfirmDialog(null,
                    "Do you want to save this score to your user profile?",
                    "Confirm score save", JOptionPane.YES_NO_OPTION, 
                    JOptionPane.QUESTION_MESSAGE);
            if (input == 0) {
                try {//saves users score to database
                    database.updateTbl("UPDATE UserResults SET APSup = " + score + " " +
                            "WHERE Username = '" + LoginPage.getUserLoggedIn() + "'");//stores user score in access database
                } catch (SQLException ex) {
                    System.out.println(ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, cal.getError());//shows error message
        }
    }//GEN-LAST:event_btnCalculateActionPerformed
    
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        Home h = new Home();
        h.setVisible(true);
        h.setSize(800,550);
        h.setResizable(false);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculateAPSPageUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculateAPSPageUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculateAPSPageUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculateAPSPageUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculateAPSPageUP().setVisible(true);
                
            }
        });
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEnglish;
    private javax.swing.JLabel lblFal;
    private javax.swing.JLabel lblMaths;
    private javax.swing.JLabel lblS1;
    private javax.swing.JLabel lblS2;
    private javax.swing.JLabel lblS3;
    private javax.swing.JLabel lblScore;
    private javax.swing.JTextArea txaInstructions;
    private javax.swing.JTextField txfEnglish;
    private javax.swing.JTextField txfFal;
    private javax.swing.JTextField txfMaths;
    private javax.swing.JTextField txfS1;
    private javax.swing.JTextField txfS2;
    private javax.swing.JTextField txfS3;
    // End of variables declaration//GEN-END:variables
}

