/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apscalculator;

/**
 *
 * @author admin
 */
public class DisplayDegree extends javax.swing.JFrame {

    /**
     * Creates new form DisplayDegree
     */
    private String degreeName, university;
    public DisplayDegree(String dn, String u) {//constructor
        initComponents();
        this.degreeName = dn;
        this.university = u;
        displayDetails();
    }
    
    private DisplayDegree() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDetails = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();
        btnCalcAPS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Degree Details");

        txaDetails.setEditable(false);
        txaDetails.setColumns(20);
        txaDetails.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txaDetails.setLineWrap(true);
        txaDetails.setRows(5);
        txaDetails.setText("Degree Name:\nFaculty: \nUniversity: \nAPS Requirement:\nEnglish Requirement:\nMaths Requirement:\nScience Requirement:\nAl and Ql NBT Score Required:\nMathamatics NBT Score Required:\nAdditional Requirements:\n");
        txaDetails.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txaDetails);

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCalcAPS.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCalcAPS.setText("Calculate my APS for this degree");
        btnCalcAPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcAPSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(jLabel1)
                        .addGap(0, 272, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCalcAPS)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcAPS)
                    .addComponent(btnBack))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private DegreesManager d = new DegreesManager();
    private void displayDetails(){//customizes text area based on details of a specific degree
        Degree matchedDegree = d.matchDegree(degreeName, university);
        txaDetails.setText("Degree Name: "+ matchedDegree.getDegreeName() +"\n" +
        "Faculty: " + matchedDegree.getFaculty() + "\n" +
        "University: " + matchedDegree.getUniversity() + "\n" +
        "APS Requirement: " + matchedDegree.getApsR() + "\n" +
        "English Requirement: " + matchedDegree.getEnglishR()+ "\n" +
        "Maths Requirement: " + matchedDegree.getMathsR() + "\n" +
        "Science Requirement: " + matchedDegree.getScienceR() + "\n" +
        "Al and Ql NBT Score Required: " + matchedDegree.getAlQlNbt() + "\n" +
        "Mathamatics NBT Score Required: " + matchedDegree.getMathamaticsNbt() + "\n" +
        "Additional Requirements: " + matchedDegree.getAdditional());
    }
    
    private void btnCalcAPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcAPSActionPerformed
        //redirects user to university calculation page for the degree cureently displayed
        if (university.equals("University of Cape Town")) {
            this.dispose();
            CalculateAPSPageUCT cal = new CalculateAPSPageUCT();
            cal.setSize(800, 550);
            cal.setResizable(false);
            cal.setVisible(true);
        } else if (university.equals("University of Pretoria")) {
            CalculateAPSPageUP cal = new CalculateAPSPageUP();
            cal.setSize(800, 550);
            cal.setResizable(false);
            cal.setVisible(true);
        } if (university.equals("University of Witwaterstrand")) {
            CalculateAPSPageWITS cal = new CalculateAPSPageWITS();
            cal.setSize(800, 550);
            cal.setResizable(false);
            cal.setVisible(true);
        }
    }//GEN-LAST:event_btnCalcAPSActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        ListOfDegrees l = new ListOfDegrees();
        l.setVisible(true);
        l.setSize(800, 550);
        l.setResizable(false);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayDegree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayDegree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayDegree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayDegree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayDegree().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCalcAPS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaDetails;
    // End of variables declaration//GEN-END:variables
}
